title: "Juliana Quigua Chinchilla"
url: "http://julianaquigua.com"
logo: "./IMG_3561.jpeg"
theme: "jekyll-theme-minimal"
description: "<a href='mailto:julianaquigua@hotmail.com'>Email</a> | <a href='https://www.linkedin.com/in/juliana-quigua-chinchilla-b9567918a/' target='_blank'>LinkedIn</a> | <a href='https://twitter.com/juliana_quigua1?lang=es' target='_blank'>X</a>"

auto_dark_mode: true





