title: Juliana Quigua Chinchilla
url: 'http://julianaquigua.com'
logo: ./IMG_3561.jpeg
theme: jekyll-theme-minimal
description: Email:julianaquigua@hotmail.com
Linkedin: https://www.linkedin.com/in/juliana-quigua-chinchilla-b9567918a/ 
Twitter: https://twitter.com/juliana_quigua1?lang=es

auto_dark_mode: true





