title: Juliana Quigua Chinchilla
url: 'http://julianaquigua.com'
logo: ./IMG_3561.jpeg
theme: jekyll-theme-minimal


## Contact
position: Quantitative Research Assistant
affiliation: Young Lives, University of Oxford.
email: julianaquigua (at) hotmail.com
google_scholar: https://scholar.google.com/
cv_link: assets/files/curriculum_vitae.pdf
linkedin: https://www.linkedin.com/in/juliana-quigua-chinchilla-b9567918a/
twitter: https://twitter.com/juliana_quigua1?lang=es
auto_dark_mode: true





