title: Juliana Quigua Chinchilla
logo: ./IMG_3561.jpeg
description: I am currently a quantitative research assistant at [Young Lives, University of Oxford.](https://www.younglives.org.uk) 
Previously a research fellow at the Inter-American Bank. I hold a B.A. and M.A. in Economics from Universidad de los Andes (Colombia). 
theme: jekyll-theme-minimal


## Contact
position: Quantitative research assistant
affiliation: Young Lives, University of Oxford
email: julianaquigua (at) hotmail.com
google_scholar: https://scholar.google.com/
cv_link: assets/files/curriculum_vitae.pdf
linkedin: https://www.linkedin.com/in/juliana-quigua-chinchilla-b9567918a/
twitter: https://twitter.com/juliana_quigua1?lang=es
auto_dark_mode: true





